version: '2'
services:
  nginx:
      restart: always 
      build:
        dockerfile: Dockerfile
        context: ./nginx
      ports:
          - '10.106.137.210:80:80'
  flask:
      restart: always
      build:
        dockerfile: Dockerfile
        context: ./flask
      ports:
          - '10.106.137.210:5000:5000'
  apache:
      restart: always
      build:
        dockerfile: Dockerfile
        context: ./apache
      ports:
          - '10.106.137.210:8080:8080'
  ubuntu1: 
      restart: always
      build:
        dockerfile: Dockerfile
        context: ./ubuntu
      ports:
          - '10.106.137.211:22:22'
  ubuntu2:                                                                                                                        
      restart: always                                                                                                            
      build:                                                                                                                     
        dockerfile: Dockerfile                                                                                                   
        context: ./ubuntu                                                                                                        
      ports:                                                                                                                     
          - '10.106.137.212:22:22' 
