#!/usr/bin/perl
use strict;
use CGI qw(:standard);

my $query=$ENV{QUERY_STRING};
my $text="This page is generated by apache server running on 192.168.102.12, from /cgi-bin/char1.pl";
print header;
#print "<B>Query string = \"$query\"</B>";
my($name, $value) = split(/=/, $query);
print start_html;
for(my $count = 0; $count < $value; $count++)
{
	print "a";
}
print end_html;
