#!/usr/bin/perl
use strict;
use CGI qw(:standard);

my $query=$ENV{QUERY_STRING};
my $text="This page is generated by apache server running on Roy_Linux (10.102.34.21), from /cgi-bin/test.pl";
print header;
#print "<B>Query string = \"$query\"</B>";
my($name, $value) = split(/=/, $query);
print start_html;
for(my $count = 0; $count < $value; $count++)
{
	print "$count) $text\n\n";
}
print end_html;
