#!/usr/bin/perl -w

my %queryString = ();
my $qwStr = $ENV{"QUERY_STRING"};
my @parts = split(/\&/, $qwStr);
my $raw = 0;

foreach $part (@parts) {
    ($name, $value) = split(/\=/, $part);
    $queryString{"$name"} = $value;
}

print "HTTP/1.1 200 OK\r\n";
print "Date: Mon, 23 Nov 2015 14:34:01 GMT\r\n";
print "Server: Unicode CGI Script\r\n";

if ($queryString{"case"} eq '1') {
    my $str = "This is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    my $len = length($str);

    print "Content-Length: $len\r\n\r\n";
    print "$str";
}

if ($queryString{"case"} eq '2') {
    my $str = "Start jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络jbvdjvbajvbeilrvbaeuvbebve网络 END";
    my $len = length($str);

    print "Connection: Close\r\n";
    print "Content-Length: $len\r\n\r\n";
    print "$str";
}

if ($queryString{"case"} eq '3') {
    my $str = "This is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscalerThis is a netscalerThis is a netscalerThis is a netcalerThis is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a netscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    my $len = length($str);

    print "Connection: Close\r\n";
    print "Content-Length: $len\r\n\r\n";
    print "$str";
}

if ($queryString{"case"} eq '4') {
    print "Transfer-Encoding: Chunked\r\n";
    print "Connection: Close\r\n";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "5\r\n";
    print "This ";
    print "\r\n";
    print "E\r\n";
    print "is a netscaler";
    print "\r\n";
    print "25\r\n";
    print "This is a netscalerThis is a netcaler";
    print "\r\n";
    print "4F\r\n";
    print "This is a netscalerThis is a  nescalerThis is a netscalerThis is a This is a ne";
    print "\r\n";
    print "78\r\n";
    print "tscalerThis is a netscalerThis is a netscalerThis is a netscalerThis is a etscalerThis is a netscalErThis is a netscaler";
    print "\r\n";
    print "0\r\n\r\n";
}

if ($queryString{"case"} eq '6') {
    print "Transfer-Encoding: Chunked\r\n";
    print "Connection: Close\r\n";
    print "\r\n";
    my $i = 1;
    while ($i <= 200) {
        #$str = "ネットワーク ";
        $str = "你好ネa";
        $hex_len = sprintf("%x", length($str));
        print "$hex_len\r\n";
        print "$str";
        print "\r\n";

        $str = "netscaler";
        $hex_len = sprintf("%x", length($str));
        print "$hex_len\r\n";
        print "$str";
        print "\r\n";
        
        $i++;
    }

    print "0\r\n\r\n";
}
