version: '2'
services:
  cpx:
    container_name: "cpx"
    image: "cpx:13.0-41.23"
    privileged: true
    volumes:
      - ./cpx:/var/cpx
    environment:
      - CPX_CORES=1
      - CPX_CONFIG='{"YIELD":"No"}'
      - EULA=yes
    ports:
      - '9443:9443'
      - '9080:9080'
    networks:
      vpcbr:
        ipv4_address: 10.10.10.1
  nginx:
      restart: always 
      build:
        dockerfile: Dockerfile
        context: ./nginx
      ports:
          - '80:80'
      networks: 
      vpcbr:
        ipv4_address: 10.10.10.2 

  flask:
      restart: always
      build:
        dockerfile: Dockerfile
        context: ./flask
      ports:
          - '5000:5000'
      networks:
        vpcbr:
          ipv4_address: 10.10.10.2
  apache:
      restart: always
      build:
        dockerfile: Dockerfile
        context: ./apache
      ports:
          - '8080:8080'
      networks:
        vpcbr:
          ipv4_address: 10.10.10.3
  ubuntu1: 
      restart: always
      build:
        dockerfile: Dockerfile
        context: ./ubuntu
      ports:
          - '22:22'
      networks:
        vpcbr:
          ipv4_address: 10.10.10.4
  ubuntu2:                                                                                                                        
      restart: always                                                                                                            
      build:                                                                                                                     
        dockerfile: Dockerfile                                                                                                   
        context: ./ubuntu                                                                                                        
      ports:                                                                                                                     
          - '22:22' 
      networks:
        vpcbr:
          ipv4_address: 10.10.10.5

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1
